name: easy-toolkit tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytest
      run: |
        pip install pytest
    - name: Install Pillow
      run: |
        pip install Pillow
    - name: Install easytk
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pytest
